# 主题模式
theme:
  switch: true
  default: style-light
# logo和网站图标
favicon:
  logo: /static/img/鲸鱼.png # 顶部 logo
  icon16: /static/img/鲸鱼.png
  icon32: /static/img/鲸鱼.png
  appleTouchIcon: apple-touch-icon.png # iOS 添加到桌面是图标
  webmanifest: /site.webmanifest # 应用程序清单文件
  visibilitychange: true # 是否在离开窗口时切换标题显示
  hidden: /static/img/鲸鱼.png # 离开窗口时显示图标
  showText: (/≧▽≦/)咦！又好了！ # 激活窗口时显示文字
  hideText: (●—●)网站开小差了！ # 离开窗口显示文字

top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/
  - title: menu.links
    url: /links/
  - title: menu.about
    url: /about/
  - title: 标签
    url: /tags/
  # - title: 自定义
  #   url: /customize_page/

# 用户信息 User
user:
  name: 前端小白      # 昵称，用于侧栏或其他区域标识
  first_name: 某人  # 名，用于顶部将姓和名分别显示
  last_name: 张  # 姓，
  # email: xcc6667888@163.com  # 邮箱
  domain: https://adminzhang1.github.io/  # 域名
  avatar: /static/img/avatar.jpg  # 头像
  describe: 这是一个前端小白,搞得第一个网站，记录一些文章吧 # 网站简介
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章可有可无，花里胡哨的就行，原创70%以上，部署HTTPS。 #友链交换规则
# 横幅Banner
banner:
  index:
    type: video
    bgurl: /static/img/homebg.mp4
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!
  archive:
    type: img
    bgurl: /static/img/bg1.jpg
    bannerTitle: 云间连下榻，<br>天上接行杯。
    bannerText: The article archive
  links:
    type: img
    bgurl: /static/img/bg2.jpg
    bannerTitle: 莫愁前路无知己，<br>天下谁人不识君。
    bannerText: A link to a friend's website
  about:
    type: img
    bgurl: /static/img/bg3.jpg
    bannerTitle: 自古人间留不住，<br>朱颜辞镜花辞树。
    bannerText: About me

sidebar:
  typedTextPrefix: I`m # 为固定前缀
  typedText: [ 'Web Developer' ] # 为打字效果切换条目，可设置多条，按顺序切换。
  info: # 个人信息
    - key: 地址
      val: 致远星
    - key: 年龄
      val: 22
    - key: 职业
      val: 前端小白
  social:
    - icon: fab fa-github
      url: https://github.com/adminzhang1
      name: Github
    - icon: fab fa-npm
      url: https://www.npmjs.com
      name: Npm
# 搜索
search:
  enable: true
  type: local
  preload: true
  trigger: auto
# 页脚 Footer
footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyrightYear: 2022
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00
  custom_text:
# 搜索
# search:
#   enable: true
#   type: local
#   preload: true
#   trigger: auto

baidu_push: true

# 友链 Links
links:
  - name: 面瘫小学弟
    url: https://adminzhang1.github.io/
    image: //www.imalun.com/images/avatar.jpg
    desc: 醒，亦在人间；梦，亦在人间
# 关于 ABOUT
about:
  title:  如果一切都是镜花水月，那就让这万物走向终结。如果一切皆是命中注定，那就让这世界消失殆尽。  # 标题
  introduction: name：面瘫小学弟 <br /> email：a2324086024@163.com # 个人简单描述
  blog: name：Life <br /> introduce：主要用来发表一些学习的文章和其它文章   # 博客信息
  privacy: 没有隐私，还不知道怎么让你们评论，先看着吧     # 隐私权说明
# 打赏
# reward:
#   enable: true
#   methods:
#     - name: 微信
#       path: https://static/img.lkxin.cn/tu/2022/09/22/632c11ab2f727.png
#     - name: 支付宝
#       path: https://static/img.lkxin.cn/tu/2022/09/22/632c11ab08ffc.jpg
# 版权信息 设置您的文章的分享版权
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true
# 归档页  默认下归档页时间轴卡片显示了标题和摘要信息，如果设置为 less 将只显示标题。
archive:
  type: more # less more
swup: true
# 文章目录
toc:
  enable: true # 是否开启
  list_number: true # 是否显示编号
  max_depth: 3 # 生成 TOC 的最大深度
  min_depth: 1 # 生成 TOC 的最小深度
# 图片懒加载
lazyload:
  enable: true
rightside:
  readmode: true
  aside: true

post_pagination:
  enable: true
  type: small
# 字数统计
wordcount:
  enable: true
  count: true
  time: true
cover:
  default: /static/img/block.jpg  # 封面默认显示的图片
  type: img  # 封面显示类型，可选 img || date
# 日期格式化 Date Format 用于配置主题中使用日期的格式。
datetime_foramt:
  post_card:  # 文章卡片的格式
    date: YY-MM-DD
    time: HH:mm
  post_info:  # 文章详情页里的格式
    date: MM-DD
    time: HH:mm
  archive:  # 归档分类页的格式
    date: MM-DD
    time: HH:mm
# 自定义图标 Icon
icons:
  # 主题切换图标
  sun: far fa-sun
  moon: far fa-moon
  # 首页视频播放
  play: fas fa-play
  # 邮箱
  email: far fa-envelope
  # 分类进入图标
  next: fas fa-arrow-right
  # 文章详情 日期
  calendar: far fa-calendar-alt
  # 文章详情 时间
  clock: far fa-clock
  # 文章详情 作者
  user: far fa-user
  # 返回顶部 v1.1.3+
  back_top: fas fa-arrow-up
  # 查询 v1.1.5+
  search: fas fa-search
  # 关闭 v1.1.5+
  close: fas fa-times
  # 打赏 v1.1.7+
  reward: fas fa-hand-holding-usd